[env:native]
platform = native
test_framework = unity
lib_compat_mode = off
test_build_src = true
lib_deps =
    https://github.com/fresh-fx59/esp32-pio-emulator
build_flags =
    -std=gnu++17
    -Iperipherals/ds3231/include
build_src_filter =
    +<*>
    +<../../../peripherals/ds3231/src/*>
